project:
  type: book

book:
  title: "Embrace the Majesty"
  author: "Subhojit Maji"
  date: "last-modified"
  sidebar:
    title: "SUBHOJIT<span class='icon-line'></span>MAJI"
    style: docked
    background: "#dad7eb"
    collapse-level: 1
  page-footer: 
    left: 
      - icon: c-circle
        text: "Copyright 2024, Subhojit Maji" 
    right: 
      - icon: github
        href: https://github.com/SubhojitMaji
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/subhojit-maji-7bbb29268?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app
        target: _blank
      - icon : envelope-paper-heart-fill
        href: mailto:majisubhojit198475mail.com
        target: _blank
  favicon: LOGO-3.png
  search: 
    location: sidebar
    type: overlay
  chapters:
    - index.qmd
    - intro.qmd
    - Pro-BABLE.qmd
    - AL-ZEBRA.qmd
    - PUZZLES.qmd
    - acheivements.qmd
    - part: "UDGRP's"
      chapters:
      - UDGRP 2024.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

format:
  html:
    toc: true
    toc-depth: 1
    toc-location: right
    toc-expand: false
    link-external-icon: true
    link-external-newwindow: true
    fontsize: '7'
    standalone: true
    smooth-scroll: true
    embed-resources: false
    linestretch: 1.5
    grid:
      sidebar-width: 350px
      body-width: 800px
      margin-width: 450px
      gutter-width: 1.5rem
    theme: aklight.scss
  #pdf:
  #    documentclass: scrreprt
#  image: cover.png