# Puzzles for Young Minds

::: {.callout-note collapse="true"}
## Iterated Sine 

Consider the function $f_n(x)$ defined for positive integers $n$ and real numbers $x$ by 
$f_n(x) = \sin(\sin(\sin(\cdots (\sin x)))),$
with $n$ applications of the sine function. Thus 
$f_2(x) = \sin(\sin x), \quad f_3(x) = \sin(\sin(\sin x)),$
and so on.

Let $x \in (0, \pi/2)$ be chosen, and let the sequence 
$f_1(x), f_2(x), f_3(x), \dots, f_{100}(x),$
be computed. It is found that for each fixed $x$ and for all sufficiently large $n$, we have 
$f_n(x) \approx \sqrt{\frac{3}{n}}.$
How may this phenomenon be explained?


::: {.callout-tip collapse="true"}
### Solution

$\href{https://youtu.be/qN-dj94NHNY?si=zgsGB23e6bzrYGQl}{\textbf{Video Solution}}$

:::

:::

::: {.callout-note collapse="true"}
## Maximums

Assume the quartic polynomial 
$x^4 - ax^3 + bx^2 - ax + d = 0$
has four real roots namely, $\frac{1}{2} \leq x_1, x_2, x_3, x_4 \leq 2$. Find the maximum possible value of 
$\frac{(x_1 + x_2)(x_1 + x_3)x_4}{(x_4 + x_2)(x_4 + x_3)x_1}.$

::: {.callout-tip collapse="true"}
### Solution 

$\href{https://www.youtube.com/watch?v=o-mX3byaZ5k}{\textbf{Video Solution}}$

:::
:::
:::{.callout-note collapse="true"}
## Polynomial Approximations

Prove that : 

> The set of polynomial functions on $[a,b]$ is dense in $C([a,b])$ 

:::{.callout-tip collapse="true"}
### Hints

The following problem can be rephrased as follows

> For every continuous function $f(x)$ defined on $[a,b]$ , there is a nice polynomial $p(x)$ that approximates it ie, $\forall \epsilon > 0$ there exists p(x) such that  $|f(x) - p(x)| < \epsilon \; \forall x \in [a,b]$ , these polynomials are called as $\textbf{Bernstein Polynomials}$

:::{.callout}
## Some Facts

- As there is a bijection , show that it holds for $C[(0,1)]$ and it holds true for $C[(a,b)]$
- Let's denote the k-th Binomial Coefficient of $(1+x-x)^n$ as $B_{n,k}$ = $\binom{n}{k} x^k ({1-x})^{n-k}$ . 

Then the n-th Bernstein Polynomial is $P_{f,n}(x)= \sum_{k=0}^{n} f\left(\frac{k}{n}\right) \cdot \binom{n}{k} \cdot x^k (1-x)^{n-k} = \sum_{k=0}^{n} f\left(\frac{k}{n}\right)B_{n,k}$

:::

:::
:::

