---
format: html
subtitle: "The secret handshake of information, passed down through generations."
title-block-banner: "#e0e8f0"  # Lighter blue background
title-block-banner-color: "black"
toc: false
from: markdown+emoji
target: _blank
---
# Winter UDGRP 24 {.unnumbered}

::: {.callout-note collapse="true"}
## Enumerative Combinatorics (By [Hrishik Koley](https://hrishik-koley.github.io))


> Here, we explored:
>
>* Group Theory (Geometric focus)
> * Generating Functions
> * Graph Theory
>     * Planar Graphs
>     * Perfect Graphs
>     * Ramsey's Number and Theorem
> * Lovasz-Local Theorem
> * Kuratowski's Theorem (Thanks to Aayushman Mallick & Arkaprovo Das for the presentation!)
> * Random Graphs and Ramsey's Number ([My Presentation](https://drive.google.com/file/d/1UxLhH8ogvzA7uRu-Fvv1YKaoC8QWKlkZ/view?usp=sharing) :wink:)


Resources and detailed Overview of the [Course](https://hrishik-koley.github.io/musings/enumerative_combinatorics/)
:::

::: {.callout-note collapse="true"}
## Introduction to Dynamical Systems (By [Aritrabha Majumdar](https://paulpseudoman.github.io/))

>This introductory course covered:

>* Basic Linear Algebra
>* Stability of Ordinary Differential Equations
>    * Linear Systems
>    * Non-Linear Systems (Local Theory)
>* Picard's Method of Successive Approximation
>* Maximal Interval of Existence

I also made a presentation on the [Spectral Theorem](https://drive.google.com/file/d/1bnqrIGg4x6yNU18mimoggvLsltV1oL1Q/view?usp=sharing).

Course notes: [link](https://paulpseudoman.github.io/DSnotes.pdf)
:::
